## Configuracion de Spring
spring:
  application:
    name: ms-inventory-products-opensearch

## Configuracion de Instancia 
server:
  port: 8088
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-inventory-products

##OpenSearch config
opensearch:
  host: ${OPENSEARCH_HOST}
  credentials:
    user: ${OPENSEARCH_USER}
    password: ${OPENSEARCH_PWD}
logging:
  level:
    tracer: TRACE